<a href="https://colab.research.google.com/github/prasadw350-lang/Assignments/blob/main/Steam_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

from google.colab import files
uploaded = files.upload()

Saving steam.csv to steam.csv

In [ ]:
filename = "/content/steam.csv"
df = pd.read_csv(filename)
df

,appid,name,release_date,english,developer,publisher,platforms,required_age,categories,genres,steamspy_tags,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,owners,price
0,10,Counter-Strike,2000-11-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,124534,3339,17612,317,10000000-20000000,7.19
1,20,Team Fortress Classic,1999-04-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,3318,633,277,62,5000000-10000000,3.99
2,30,Day of Defeat,2003-05-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Valve Anti-Cheat enabled,Action,FPS;World War II;Multiplayer,0,3416,398,187,34,5000000-10000000,3.99
3,40,Deathmatch Classic,2001-06-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,1273,267,258,184,5000000-10000000,3.99
4,50,Half-Life: Opposing Force,1999-11-01,1,Gearbox Software,Valve,windows;mac;linux,0,Single-player;Multi-player;Valve Anti-Cheat en...,Action,FPS;Action;Sci-fi,0,5250,288,624,415,5000000-10000000,3.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27070,1065230,Room of Pandora,2019-04-24,1,SHEN JIAWEI,SHEN JIAWEI,windows,0,Single-player;Steam Achievements,Adventure;Casual;Indie,Adventure;Indie;Casual,7,3,0,0,0,0-20000,2.09
27071,1065570,Cyber Gun,2019-04-23,1,Semyon Maximov,BekkerDev Studio,windows,0,Single-player,Action;Adventure;Indie,Action;Indie;Adventure,0,8,1,0,0,0-20000,1.69
27072,1065650,Super Star Blast,2019-04-24,1,EntwicklerX,EntwicklerX,windows,0,Single-player;Multi-player;Co-op;Shared/Split ...,Action;Casual;Indie,Action;Indie;Casual,24,0,1,0,0,0-20000,3.99
27073,1066700,New Yankee 7: Deer Hunters,2019-04-17,1,Yustas Game Studio,Alawar Entertainment,windows;mac,0,Single-player;Steam Cloud,Adventure;Casual;Indie,Indie;Casual;Adventure,0,2,0,0,0,0-20000,5.19
27074,1069460,Rune Lord,2019-04-24,1,Adept Studios GD,Alawar Entertainment,windows;mac,0,Single-player;Steam Cloud,Adventure;Casual;Indie,Indie;Casual;Adventure,0,4,0,0,0,0-20000,5.19

In [4]:
df.head()

,appid,name,release_date,english,developer,publisher,platforms,required_age,categories,genres,steamspy_tags,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,owners,price
0,10,Counter-Strike,2000-11-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,124534,3339,17612,317,10000000-20000000,7.19
1,20,Team Fortress Classic,1999-04-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,3318,633,277,62,5000000-10000000,3.99
2,30,Day of Defeat,2003-05-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Valve Anti-Cheat enabled,Action,FPS;World War II;Multiplayer,0,3416,398,187,34,5000000-10000000,3.99
3,40,Deathmatch Classic,2001-06-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,1273,267,258,184,5000000-10000000,3.99
4,50,Half-Life: Opposing Force,1999-11-01,1,Gearbox Software,Valve,windows;mac;linux,0,Single-player;Multi-player;Valve Anti-Cheat en...,Action,FPS;Action;Sci-fi,0,5250,288,624,415,5000000-10000000,3.99

In [5]:
df.tail()

,appid,name,release_date,english,developer,publisher,platforms,required_age,categories,genres,steamspy_tags,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,owners,price
27070,1065230,Room of Pandora,2019-04-24,1,SHEN JIAWEI,SHEN JIAWEI,windows,0,Single-player;Steam Achievements,Adventure;Casual;Indie,Adventure;Indie;Casual,7,3,0,0,0,0-20000,2.09
27071,1065570,Cyber Gun,2019-04-23,1,Semyon Maximov,BekkerDev Studio,windows,0,Single-player,Action;Adventure;Indie,Action;Indie;Adventure,0,8,1,0,0,0-20000,1.69
27072,1065650,Super Star Blast,2019-04-24,1,EntwicklerX,EntwicklerX,windows,0,Single-player;Multi-player;Co-op;Shared/Split ...,Action;Casual;Indie,Action;Indie;Casual,24,0,1,0,0,0-20000,3.99
27073,1066700,New Yankee 7: Deer Hunters,2019-04-17,1,Yustas Game Studio,Alawar Entertainment,windows;mac,0,Single-player;Steam Cloud,Adventure;Casual;Indie,Indie;Casual;Adventure,0,2,0,0,0,0-20000,5.19
27074,1069460,Rune Lord,2019-04-24,1,Adept Studios GD,Alawar Entertainment,windows;mac,0,Single-player;Steam Cloud,Adventure;Casual;Indie,Indie;Casual;Adventure,0,4,0,0,0,0-20000,5.19

In [6]:
df.shape

(27075, 18)

In [7]:
df.columns

Index(['appid', 'name', 'release_date', 'english', 'developer', 'publisher',
       'platforms', 'required_age', 'categories', 'genres', 'steamspy_tags',
       'achievements', 'positive_ratings', 'negative_ratings',
       'average_playtime', 'median_playtime', 'owners', 'price'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27075 entries, 0 to 27074
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   appid             27075 non-null  int64
 1   name              27075 non-null  object
 2   release_date      27075 non-null  object
 3   english           27075 non-null  int64
 4   developer         27074 non-null  object
 5   publisher         27061 non-null  object
 6   platforms         27075 non-null  object
 7   required_age      27075 non-null  int64
 8   categories        27075 non-null  object
 9   genres            27075 non-null  object
 10  steamspy_tags     27075 non-null  object
 11  achievements      27075 non-null  int64
 12  positive_ratings  27075 non-null  int64
 13  negative_ratings  27075 non-null  int64
 14  average_playtime  27075 non-null  int64
 15  median_playtime   27075 non-null  int64
 16  owners            27075 non-null  object
 17  price             27075 non-null  float64
dtypes: float64(1), int64(8), object(9)
memory usage: 3.7+ MB

In [9]:
df.describe()

,appid,english,required_age,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,price
count,2.707500e+04,27075.000000,27075.000000,27075.000000,2.707500e+04,27075.000000,27075.000000,27075.00000,27075.000000
mean,5.962035e+05,0.981127,0.354903,45.248864,1.000559e+03,211.027147,149.804949,146.05603,6.078193
std,2.508942e+05,0.136081,2.406044,352.670281,1.898872e+04,4284.938531,1827.038141,2353.88008,7.874922
min,1.000000e+01,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.00000,0.000000
25%,4.012300e+05,1.000000,0.000000,0.000000,6.000000e+00,2.000000,0.000000,0.00000,1.690000
50%,5.990700e+05,1.000000,0.000000,7.000000,2.400000e+01,9.000000,0.000000,0.00000,3.990000
75%,7.987600e+05,1.000000,0.000000,23.000000,1.260000e+02,42.000000,0.000000,0.00000,7.190000
max,1.069460e+06,1.000000,18.000000,9821.000000,2.644404e+06,487076.000000,190625.000000,190625.00000,421.990000

In [10]:
df.dtypes

appid                 int64
name                 object
release_date         object
english               int64
developer            object
publisher            object
platforms            object
required_age          int64
categories           object
genres               object
steamspy_tags        object
achievements          int64
positive_ratings      int64
negative_ratings      int64
average_playtime      int64
median_playtime       int64
owners               object
price               float64
dtype: object

In [11]:
df.isnull().sum()

appid                0
name                 0
release_date         0
english              0
developer            1
publisher           14
platforms            0
required_age         0
categories           0
genres               0
steamspy_tags        0
achievements         0
positive_ratings     0
negative_ratings     0
average_playtime     0
median_playtime      0
owners               0
price                0
dtype: int64

In [12]:
df.nunique()

appid               27075
name                27033
release_date         2619
english                 2
developer           17112
publisher           14353
platforms               7
required_age            6
categories           3333
genres               1552
steamspy_tags        6423
achievements          410
positive_ratings     2800
negative_ratings     1492
average_playtime     1345
median_playtime      1312
owners                 13
price                 282
dtype: int64

In [13]:
df.sample(5)

,appid,name,release_date,english,developer,publisher,platforms,required_age,categories,genres,steamspy_tags,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,owners,price
13244,589530,Hakuoki: Kyoto Winds / 薄桜鬼 真改 風ノ章 / 薄櫻鬼 真改 風之章,2017-08-24,1,Idea Factory;Design Factory,Idea Factory International,windows,0,Single-player;Steam Achievements;Full controll...,Violent;Adventure,Adventure;Visual Novel;Violent,36,312,53,0,0,20000-50000,22.99
25476,973690,Antrum,2019-02-14,1,Blank Name Games,Blank Name Games,windows;mac;linux,0,Single-player;Partial Controller Support;Steam...,Action;Adventure;Casual;Indie,Action;Indie;Casual,0,1,0,0,0,0-20000,5.79
16118,679430,Skyraine,2017-09-01,1,DHTstudios LLC,DHTstudios LLC,windows,0,Single-player;Multi-player;Local Multi-Player;...,Indie;Strategy,Strategy;Indie;Platformer,32,23,11,0,0,0-20000,1.59
20184,795120,To The Capital 2,2019-02-20,1,Kormishenkov Anton,Kormishenkov Anton,windows;linux,0,Single-player;Partial Controller Support,Adventure;Indie;RPG,Adventure;Indie;RPG,0,2,1,0,0,0-20000,3.99
6503,393550,The Journey Back,2015-08-12,1,Erwin Wolf,MarWin Studios,windows;mac;linux,0,Single-player;Steam Trading Cards,Adventure;Casual;Indie,Adventure;Indie;Casual,0,18,7,0,0,0-20000,1.59

In [14]:
df.value_counts()

appid    name                            release_date  english  developer         publisher             platforms          required_age  categories                                                                                                                          genres                  steamspy_tags                 achievements  positive_ratings  negative_ratings  average_playtime  median_playtime  owners             price
1069460  Rune Lord                       2019-04-24    1        Adept Studios GD  Alawar Entertainment  windows;mac        0             Single-player;Steam Cloud                                                                                                           Adventure;Casual;Indie  Indie;Casual;Adventure        0             4                 0                 0                 0                0-20000            5.19     1
10       Counter-Strike                  2000-11-01    1        Valve             Valve                 windows;mac;linux  0             Multi-player;Online Multi-Player;Local Multi-Player;Valve Anti-Cheat enabled                                                        Action                  Action;FPS;Multiplayer        0             124534            3339              17612             317              10000000-20000000  7.19     1
20       Team Fortress Classic           1999-04-01    1        Valve             Valve                 windows;mac;linux  0             Multi-player;Online Multi-Player;Local Multi-Player;Valve Anti-Cheat enabled                                                        Action                  Action;FPS;Multiplayer        0             3318              633               277               62               5000000-10000000   3.99     1
30       Day of Defeat                   2003-05-01    1        Valve             Valve                 windows;mac;linux  0             Multi-player;Valve Anti-Cheat enabled                                                                                               Action                  FPS;World War II;Multiplayer  0             3416              398               187               34               5000000-10000000   3.99     1
40       Deathmatch Classic              2001-06-01    1        Valve             Valve                 windows;mac;linux  0             Multi-player;Online Multi-Player;Local Multi-Player;Valve Anti-Cheat enabled                                                        Action                  Action;FPS;Multiplayer        0             1273              267               258               184              5000000-10000000   3.99     1
                                                                                                                                                                                                                                                                                                                                                                                                                                                   ..
220      Half-Life 2                     2004-11-16    1        Valve             Valve                 windows;mac;linux  0             Single-player;Steam Achievements;Steam Trading Cards;Captions available;Partial Controller Support;Steam Cloud;Includes Source SDK  Action                  FPS;Action;Sci-fi             33            67902             2419              691               402              10000000-20000000  7.19     1
130      Half-Life: Blue Shift           2001-06-01    1        Gearbox Software  Valve                 windows;mac;linux  0             Single-player                                                                                                                       Action                  FPS;Action;Sci-fi             0             3822              420               361               205              5000000-10000000   3.99     1
80       Counter-Strike: Condition Zero  2004-03-01    1        Valve             Valve                 windows;mac;linux  0             Single-player;Multi-player;Valve Anti-Cheat enabled                                                                                 Action                  Action;FPS;Multiplayer        0             12120             1439              427               43               10000000-20000000  7.19     1
70       Half-Life                       1998-11-08    1        Valve             Valve                 windows;mac;linux  0             Single-player;Multi-player;Online Multi-Player;Steam Cloud;Valve Anti-Cheat enabled                                                 Action                  FPS;Classic;Action            0             27755             1100              1300              83               5000000-10000000   7.19     1
60       Ricochet                        2000-11-01    1        Valve             Valve                 windows;mac;linux  0             Multi-player;Online Multi-Player;Valve Anti-Cheat enabled                                                                           Action                  Action;FPS;Multiplayer        0             2758              684               175               10               5000000-10000000   3.99     1
Name: count, Length: 27061, dtype: int64